import React, { useState } from 'react';
import { Download, X, Settings2, FileText, Type, Layout } from 'lucide-react';
import { Button } from './ui/Button';

const PdfDownloadModal = ({ isOpen, onClose, initialSettings, onSave }) => {
    const defaultSettings = {
        fileName: "week_routine",
        universityName: "North Western University",
        departmentName: "Department of Computer Science and Engineering",
        semesterName: "Spring 2026",
        additionalText: "",
        footerText: "Generated by NWU Smart Routine System",
        fontStyle: "helvetica",
        fontSize: 7,
        headerFontSize: 16
    };

    const [settings, setSettings] = useState(initialSettings || defaultSettings);

    // Update internal state if initialSettings changes from outside
    React.useEffect(() => {
        if (initialSettings) {
            setSettings(initialSettings);
        }
    }, [initialSettings]);

    if (!isOpen) return null;

    const handleChange = (e) => {
        const { name, value, type } = e.target;
        setSettings(prev => ({
            ...prev,
            [name]: type === 'number' ? Number(value) : value
        }));
    };

    const handleSave = () => {
        onSave(settings);
        onClose();
    };

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm">
            <div className="bg-card w-full max-w-lg rounded-xl shadow-xl border border-border overflow-hidden">
                <div className="flex justify-between items-center p-5 border-b border-border bg-muted/20">
                    <h3 className="text-xl font-bold flex items-center gap-2 text-foreground">
                        <Settings2 className="h-5 w-5 text-indigo-500" />
                        PDF Export Settings
                    </h3>
                    <Button variant="ghost" size="icon" onClick={onClose} className="hover:bg-destructive/10 hover:text-destructive transition-colors">
                        <X className="h-5 w-5" />
                    </Button>
                </div>

                <div className="p-6 space-y-6 max-h-[70vh] overflow-y-auto">

                    {/* Header Customization */}
                    <div className="space-y-4">
                        <h4 className="font-semibold flex items-center gap-2 text-muted-foreground uppercase text-xs tracking-wider">
                            <Layout className="h-4 w-4" /> Header Content
                        </h4>

                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                            <div>
                                <label className="block text-sm font-medium mb-1.5 line-clamp-1">File Name</label>
                                <div className="relative">
                                    <input
                                        type="text"
                                        name="fileName"
                                        value={settings.fileName}
                                        onChange={handleChange}
                                        placeholder="e.g. week_routine"
                                        className="w-full p-2.5 pr-12 rounded-lg border border-input bg-background text-sm focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 outline-none transition-all placeholder:text-muted-foreground/50"
                                    />
                                    <span className="absolute right-3 top-1/2 -translate-y-1/2 text-sm text-muted-foreground pointer-events-none">
                                        .pdf
                                    </span>
                                </div>
                            </div>
                            <div>
                                <label className="block text-sm font-medium mb-1.5 line-clamp-1">University / Organization Name</label>
                                <input
                                    type="text"
                                    name="universityName"
                                    value={settings.universityName}
                                    onChange={handleChange}
                                    placeholder="e.g. North Western University"
                                    className="w-full p-2.5 rounded-lg border border-input bg-background text-sm focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 outline-none transition-all placeholder:text-muted-foreground/50"
                                />
                            </div>
                        </div>

                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-4">
                            <div>
                                <label className="block text-sm font-medium mb-1.5">Department Name</label>
                                <input
                                    type="text"
                                    name="departmentName"
                                    value={settings.departmentName}
                                    onChange={handleChange}
                                    placeholder="e.g. Dept. of CSE"
                                    className="w-full p-2.5 rounded-lg border border-input bg-background text-sm focus:ring-2 focus:ring-indigo-500 outline-none transition-all"
                                />
                            </div>
                            <div>
                                <label className="block text-sm font-medium mb-1.5">Semester Name</label>
                                <input
                                    type="text"
                                    name="semesterName"
                                    value={settings.semesterName}
                                    onChange={handleChange}
                                    placeholder="e.g. Spring 2026"
                                    className="w-full p-2.5 rounded-lg border border-input bg-background text-sm focus:ring-2 focus:ring-indigo-500 outline-none transition-all"
                                />
                            </div>
                        </div>

                        <div className="mt-4">
                            <label className="block text-sm font-medium mb-1.5">Additional Top-Right Text</label>
                            <input
                                type="text"
                                name="additionalText"
                                value={settings.additionalText}
                                onChange={handleChange}
                                placeholder="e.g. Version 2.0 (Optional)"
                                className="w-full p-2.5 rounded-lg border border-input bg-background text-sm focus:ring-2 focus:ring-indigo-500 outline-none transition-all"
                            />
                        </div>
                    </div>

                    <hr className="border-border" />

                    {/* Typography Customization */}
                    <div className="space-y-4">
                        <h4 className="font-semibold flex items-center gap-2 text-muted-foreground uppercase text-xs tracking-wider">
                            <Type className="h-4 w-4" /> Typography
                        </h4>

                        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                            <div className="md:col-span-1">
                                <label className="block text-sm font-medium mb-1.5">Font Style</label>
                                <select
                                    name="fontStyle"
                                    value={settings.fontStyle}
                                    onChange={handleChange}
                                    className="w-full p-2.5 rounded-lg border border-input bg-background text-sm focus:ring-2 focus:ring-indigo-500 outline-none transition-all"
                                >
                                    <option value="helvetica">Helvetica</option>
                                    <option value="times">Times New Roman</option>
                                    <option value="courier">Courier</option>
                                </select>
                            </div>
                            <div>
                                <label className="block text-sm font-medium mb-1.5">Title Font Size</label>
                                <input
                                    type="number"
                                    name="headerFontSize"
                                    value={settings.headerFontSize}
                                    onChange={handleChange}
                                    min="10"
                                    max="36"
                                    className="w-full p-2.5 rounded-lg border border-input bg-background text-sm focus:ring-2 focus:ring-indigo-500 outline-none transition-all"
                                />
                            </div>
                            <div>
                                <label className="block text-sm font-medium mb-1.5">Table Font Size</label>
                                <input
                                    type="number"
                                    name="fontSize"
                                    value={settings.fontSize}
                                    onChange={handleChange}
                                    min="4"
                                    max="14"
                                    step="0.5"
                                    className="w-full p-2.5 rounded-lg border border-input bg-background text-sm focus:ring-2 focus:ring-indigo-500 outline-none transition-all"
                                />
                            </div>
                        </div>
                    </div>

                    <hr className="border-border" />

                    {/* Footer Customization */}
                    <div className="space-y-4">
                        <h4 className="font-semibold flex items-center gap-2 text-muted-foreground uppercase text-xs tracking-wider">
                            <FileText className="h-4 w-4" /> Footer Content
                        </h4>

                        <div>
                            <label className="block text-sm font-medium mb-1.5">Footer Text</label>
                            <input
                                type="text"
                                name="footerText"
                                value={settings.footerText}
                                onChange={handleChange}
                                placeholder="e.g. Generated by Smart Routine System"
                                className="w-full p-2.5 rounded-lg border border-input bg-background text-sm focus:ring-2 focus:ring-indigo-500 outline-none transition-all"
                            />
                        </div>
                    </div>

                </div>

                <div className="flex justify-end items-center gap-3 p-5 border-t border-border bg-muted/10">
                    <Button variant="outline" onClick={onClose} className="px-5">
                        Cancel
                    </Button>
                    <Button onClick={handleSave} className="px-6 bg-indigo-600 hover:bg-indigo-700 text-white shadow-md">
                        <Settings2 className="mr-2 h-4 w-4" />
                        Save Settings
                    </Button>
                </div>
            </div>
        </div>
    );
};

export default PdfDownloadModal;
